import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import Avatar from '@/Components/Avatar';
import { money } from '@/utils/money';
import { Head, Link } from '@inertiajs/react';
import { ArrowRight, ListChecks, Plus, WalletCards } from 'lucide-react';

const icons = ["⌂", "✈", "♜", "✦"];
export default function Index({ trackers }) {
    const total = trackers.reduce((sum, tracker) => sum + tracker.current_user_balance_minor, 0);
    return <AuthenticatedLayout header={<div className="flex items-center justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><span className="flex size-14 shrink-0 items-center justify-center rounded-2xl bg-[#d8f7e5] text-[#21c76a]"><WalletCards size={27}/></span><div className="min-w-0"><h1 className="truncate font-display text-3xl font-bold tracking-tight">Trackers</h1><p className="mt-1 truncate text-sm text-slate-500">Manage your shared expenses</p></div></div><Link href={route('trackers.create')} className="ss-button h-11 shrink-0 gap-1.5 px-3 sm:px-4"><Plus size={18}/><span className="sm:hidden">New</span><span className="hidden sm:inline">Create tracker</span></Link></div>}>
        <Head title="Trackers" />
        <div className="page-wrap pb-10">
            <section className="grid gap-4 sm:grid-cols-[minmax(0,1fr)_12rem]"><div className="rounded-[1.8rem] border-2 border-[#2ecc70] bg-[#effcf4] p-6"><p className="eyebrow">Total balance</p><p className={`mt-3 font-display text-4xl font-bold ${total >= 0 ? 'text-[#22c76a]' : 'text-rose-600'}`}>{money(total, trackers[0]?.currency_code || 'PHP')}</p><p className="mt-3 text-sm font-medium text-[#0d9b4c]">↗ {total >= 0 ? 'Due to you' : 'Amount due across trackers'}</p></div><div className="flex items-center gap-3 rounded-[1.5rem] border border-slate-200 bg-white px-5 py-4 shadow-[0_3px_10px_rgba(15,23,42,.035)] sm:flex-col sm:items-start sm:justify-center"><span className="flex size-10 items-center justify-center rounded-xl bg-[#e8faef] text-lg">⚑</span><div><p className="eyebrow">Active</p><p className="mt-1 font-display text-2xl font-bold">{trackers.length}</p><p className="mt-0.5 text-xs text-slate-500">trackers</p></div></div></section>
            <div className="mt-10 flex items-center justify-between"><h2 className="font-display text-2xl font-bold">Your Trackers</h2><Link href={route('trackers.create')} className="inline-flex items-center gap-1 text-sm font-bold text-[#20c66a]">New tracker <ArrowRight size={16}/></Link></div>
            {trackers.length === 0 ? <div className="mt-5 rounded-[2rem] border border-dashed border-[#b7eeca] bg-white px-8 py-16 text-center"><span className="mx-auto flex size-16 items-center justify-center rounded-3xl bg-[#dcf9e7] text-[#24c96b]"><ListChecks size={30}/></span><h3 className="mt-5 text-xl font-bold">No Trackers yet</h3><p className="mx-auto mt-2 max-w-sm text-slate-500">Create a tracker for a trip, household, dinner, or any expense you want to share fairly.</p><Link href={route('trackers.create')} className="ss-button mt-6">Create your first tracker</Link></div> : <div className="mt-5 grid gap-5 lg:grid-cols-2">{trackers.map((tracker, index) => { const value = tracker.current_user_balance_minor; const state = value > 0 ? "You're owed" : value < 0 ? 'You owe' : 'Settled up'; const valueStyle = value > 0 ? 'text-[#0d9c4a]' : value < 0 ? 'text-rose-600' : 'text-slate-600'; return <Link key={tracker.id} href={route('trackers.show', tracker.id)} className="ss-card block p-5 transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 gap-4"><span className={`flex size-16 shrink-0 items-center justify-center rounded-2xl text-3xl ${index % 3 === 0 ? 'bg-[#dbeafe]' : index % 3 === 1 ? 'bg-[#fff2c6]' : 'bg-[#ffe4e8]'}`}>{icons[index % icons.length]}</span><div className="min-w-0"><h3 className="truncate font-display text-xl font-bold">{tracker.name}</h3><p className="mt-1 truncate text-sm text-slate-500">{tracker.description || 'Shared expense tracker'}</p></div></div><span className="rounded-full bg-[#eafaf0] px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-[#11a84f]">Active</span></div><div className="mt-6 flex items-end justify-between border-t border-slate-100 pt-4"><div><p className="text-xs text-slate-400">Shared balance</p><p className={`mt-1 text-xl font-bold ${valueStyle}`}>{state} {money(value, tracker.currency_code)}</p></div><div className="flex -space-x-2">{Array.from({ length: Math.min(tracker.members_count, 3) }).map((_, memberIndex) => <Avatar key={memberIndex} name={`M ${memberIndex}`} index={memberIndex} size="sm"/>)}{tracker.members_count > 3 && <span className="flex size-8 items-center justify-center rounded-full border-2 border-white bg-slate-100 text-[10px] font-bold text-slate-500">+{tracker.members_count - 3}</span>}</div></div></Link>; })}</div>}
        </div>
    </AuthenticatedLayout>;
}
