import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import Avatar from '@/Components/Avatar';
import BalanceCard from '@/Components/BalanceCard';
import { money, shortDate } from '@/utils/money';
import { Head, Link, usePage } from '@inertiajs/react';
import { ChevronLeft, ChevronRight, MessageCircle, Users } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';

const category = ['🍴', '🛒', '⛽', '🎬'];
export default function Show({ tracker, membership, members, expenses, debts, currentUserId, unreadMessagesCount }) {
    const [tab, setTab] = useState('transactions'); const { flash } = usePage().props;
    const [unreadMessages, setUnreadMessages] = useState(unreadMessagesCount);
    const ownBalance = members.find((member) => member.id === currentUserId)?.balance_minor || 0;
    const people = useMemo(() => Object.fromEntries(members.map((member) => [member.id, member.name])), [members]);
    useEffect(() => setUnreadMessages(unreadMessagesCount), [unreadMessagesCount]);
    useEffect(() => {
        if (!window.Echo) return undefined;
        const channel = window.Echo.private(`tracker.${tracker.id}`);
        channel.listen('.tracker.message.created', ({ message }) => {
            if (message.author.id !== currentUserId) setUnreadMessages((count) => count + 1);
        });
        return () => window.Echo.leave(`private-tracker.${tracker.id}`);
    }, [tracker.id, currentUserId]);
    return <AuthenticatedLayout header={<div className="flex items-center justify-between"><Link href={route('trackers.index')} className="flex size-10 items-center justify-center rounded-full text-slate-700"><ChevronLeft size={28}/></Link><div className="min-w-0 text-center"><h1 className="truncate font-display text-xl font-bold">{tracker.name}</h1><p className="mt-0.5 text-[10px] font-bold uppercase tracking-[.14em] text-slate-500">{members.length} members · Active</p></div><Link href={route('trackers.members.index', tracker.id)} className="flex size-10 items-center justify-center rounded-full text-slate-700"><Users size={22}/></Link></div>}>
        <Head title={tracker.name} />
        <div className="page-wrap max-w-4xl">{flash.success && <div className="mb-4 rounded-2xl bg-[#e9fbf0] px-4 py-3 text-sm font-medium text-[#0d9b4b]">{flash.success}</div>}
            <BalanceCard balance={ownBalance} currency={tracker.currency_code} settlementHref={route('trackers.settlements.create', tracker.id)} />
            <Link href={route('trackers.conversation.index', tracker.id)} className="mt-4 flex items-center gap-4 rounded-[1.45rem] border border-[#c8f1d8] bg-white px-5 py-4 shadow-[0_3px_10px_rgba(15,23,42,.035)] transition hover:border-[#8ce4af] hover:bg-[#f9fffb]">
                <span className="relative flex size-11 items-center justify-center rounded-2xl bg-[#e8faef] text-[#16b85b]"><MessageCircle size={21}/>{unreadMessages > 0 && <span className="absolute -right-2 -top-2 flex min-w-5 items-center justify-center rounded-full border-2 border-white bg-rose-500 px-1 text-[10px] font-bold leading-5 text-white" aria-label={`${unreadMessages} unread messages`}>{unreadMessages > 99 ? '99+' : unreadMessages}</span>}</span>
                <span className="min-w-0 flex-1"><span className="block font-display text-lg font-bold text-slate-900">Conversation</span><span className="mt-0.5 block truncate text-sm text-slate-500">Message everyone in this tracker</span></span>
                <span className="flex items-center gap-2"><span className="text-xs font-bold text-rose-500">{unreadMessages > 0 ? `${unreadMessages > 99 ? '99+' : unreadMessages} new` : ''}</span><ChevronRight size={20} className="shrink-0 text-[#26bf67]"/></span>
            </Link>
            <div className="mt-7 flex border-b border-slate-200"><button onClick={() => setTab('transactions')} className={`flex-1 border-b-2 px-3 py-4 text-xs font-bold uppercase tracking-[.14em] ${tab === 'transactions' ? 'border-[#2ecc70] text-[#16b85b]' : 'border-transparent text-slate-400'}`}>Transactions</button><button onClick={() => setTab('balances')} className={`flex-1 border-b-2 px-3 py-4 text-xs font-bold uppercase tracking-[.14em] ${tab === 'balances' ? 'border-[#2ecc70] text-[#16b85b]' : 'border-transparent text-slate-400'}`}>Balances</button></div>
            {tab === 'transactions' && <section className="mt-7"><div className="flex items-center justify-between gap-3"><h2 className="font-display text-2xl font-bold">Recent Transactions</h2>{membership.can_manage_finances && <Link href={route('trackers.expenses.create', tracker.id)} className="ss-button h-11 shrink-0 px-4">Add expense</Link>}</div>{expenses.length === 0 ? <div className="mt-5 ss-card p-10 text-center"><p className="font-bold">No Expenses yet</p><p className="mt-1 text-sm text-slate-500">Add the first shared expense to begin.</p>{membership.can_manage_finances && <Link href={route('trackers.expenses.create', tracker.id)} className="ss-button mt-5">Add expense</Link>}</div> : <div className="mt-4 overflow-hidden rounded-[1.65rem] border border-slate-100 bg-white">{expenses.map((expense, index) => <Link key={expense.id} href={route('trackers.expenses.show', [tracker.id, expense.id])} className="flex items-center gap-4 border-b border-slate-100 px-4 py-4 last:border-0 hover:bg-slate-50"><span className={`flex size-14 shrink-0 items-center justify-center rounded-2xl text-2xl ${index % 2 ? 'bg-[#fff1df]' : 'bg-[#e6faef]'}`}>{category[index % category.length]}</span><div className="min-w-0 flex-1"><h3 className="truncate font-display text-lg font-bold">{expense.description}</h3><p className="mt-1 text-sm text-slate-500">Paid by {expense.payer.name} · {shortDate(expense.expense_date)}</p>{expense.comments_count > 0 && <p className="mt-1 flex items-center gap-1 text-xs font-medium text-[#1bbb61]"><MessageCircle size={13}/>{expense.comments_count} comment{expense.comments_count === 1 ? '' : 's'}</p>}</div><div className="text-right"><p className="font-display text-lg font-bold">{money(expense.amount_minor, tracker.currency_code)}</p><p className="mt-1 text-xs text-slate-400">{shortDate(expense.expense_date)}</p></div><ChevronRight size={17} className="hidden text-slate-300 sm:block"/></Link>)}</div>}<p className="mt-8 text-center text-sm text-slate-400">Showing recent tracker activity</p></section>}
            {tab === 'balances' && <section className="mt-7"><h2 className="font-display text-2xl font-bold">Member Balances</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{members.map((member, index) => { const amount = member.balance_minor; return <div key={member.id} className="ss-card flex items-center gap-3 p-4"><Avatar name={member.id === currentUserId ? 'You' : member.name} index={index}/><div className="min-w-0 flex-1"><p className="truncate font-bold">{member.id === currentUserId ? 'You' : member.name}</p><p className="mt-0.5 text-[10px] font-bold uppercase tracking-wider text-slate-400">{member.role}</p></div><div className="text-right"><p className={`text-[10px] font-bold uppercase ${amount > 0 ? 'text-[#0ea44e]' : amount < 0 ? 'text-rose-500' : 'text-slate-400'}`}>{amount > 0 ? 'Due to you' : amount < 0 ? 'Amount due' : 'Settled'}</p><p className={`font-display text-xl font-bold ${amount > 0 ? 'text-[#0aa446]' : amount < 0 ? 'text-rose-600' : 'text-slate-700'}`}>{money(amount, tracker.currency_code)}</p></div></div>; })}</div><div className="mt-7 ss-card p-5"><h3 className="font-bold">Outstanding obligations</h3>{debts.length ? <div className="mt-3 space-y-3">{debts.map((debt) => <p key={`${debt.from_user_id}-${debt.to_user_id}`} className="text-sm text-slate-600"><b>{debt.from_user_id === currentUserId ? 'You' : people[debt.from_user_id]}</b><span className="mx-2 text-slate-400">→</span><b>{debt.to_user_id === currentUserId ? 'You' : people[debt.to_user_id]}</b><strong className="ml-2 text-[#10a84f]">{money(debt.amount_minor, tracker.currency_code)}</strong></p>)}</div> : <p className="mt-2 text-sm text-slate-500">No outstanding obligations.</p>}</div></section>}
        </div>
    </AuthenticatedLayout>;
}
