import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import Avatar from '@/Components/Avatar';
import BalanceCard from '@/Components/BalanceCard';
import { money, shortDate } from '@/utils/money';
import { Head, Link, router, usePage } from '@inertiajs/react';
import { Archive, ArrowDownLeft, ArrowUpRight, ChevronLeft, ChevronRight, MessageCircle, ReceiptText, Share2, Trash2, Users } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';

const category = ['🍴', '🛒', '⛽', '🎬'];
export default function Show({ tracker, membership, members, expenses, myExpenseTotalMinor, debts, currentUserId, unreadMessagesCount, unreadNotificationsCount, personalTransactions = [] }) {
    const [tab, setTab] = useState('transactions'); const { flash } = usePage().props;
    const [unreadMessages, setUnreadMessages] = useState(unreadMessagesCount);
    const [sharing, setSharing] = useState(false);
    const myExpenses = useMemo(() => expenses.filter((expense) => Number(expense.paid_by_user_id) === Number(currentUserId)), [expenses, currentUserId]);
    const ownBalance = members.find((member) => member.id === currentUserId)?.balance_minor || 0;
    const people = useMemo(() => Object.fromEntries(members.map((member) => [member.id, member.name])), [members]);
    useEffect(() => setUnreadMessages(unreadMessagesCount), [unreadMessagesCount]);
    useEffect(() => {
        if (!window.Echo) return undefined;
        const channel = window.Echo.private(`tracker.${tracker.id}`);
        channel.listen('.tracker.message.created', ({ message }) => {
            if (message.author.id !== currentUserId) setUnreadMessages((count) => count + 1);
        });
        return () => window.Echo.leave(`private-tracker.${tracker.id}`);
    }, [tracker.id, currentUserId]);
    const archive = () => { if (window.confirm(`Archive ${tracker.name}? Its history will be kept, but no one can add expenses, members, or messages until you restore it.`)) router.patch(route('trackers.archive', tracker.id)); };
    const destroy = () => { if (window.confirm(`Delete ${tracker.name}? It will be removed from everyone’s tracker list.`)) router.delete(route('trackers.destroy', tracker.id)); };
    const destroyExpense = (expense) => { if (window.confirm(`Delete ${expense.description}? It will be removed from the trip and balances will be recalculated.`)) router.delete(route('trackers.expenses.destroy', [tracker.id, expense.id])); };
    const share = async () => {
        try {
            setSharing(true);
            const csrf = document.querySelector('meta[name="csrf-token"]')?.content || '';
            const response = await fetch(route('trackers.share-link.store', tracker.id), { method: 'POST', credentials: 'same-origin', headers: { Accept: 'application/json', 'X-CSRF-TOKEN': csrf, 'X-Requested-With': 'XMLHttpRequest' } });
            if (!response.ok) throw new Error('Could not create link');
            const { url } = await response.json();
            if (navigator.share) await navigator.share({ url });
            else { await navigator.clipboard.writeText(url); window.alert('Share link copied.'); }
        } catch (error) {
            if (error?.name !== 'AbortError') window.alert('Could not share this tracker. Please try again.');
        } finally { setSharing(false); }
    };
    return <AuthenticatedLayout header={<div className="flex items-center justify-between"><Link href={route('trackers.index')} className="flex size-10 items-center justify-center rounded-full text-slate-700"><ChevronLeft size={28}/></Link><div className="min-w-0 text-center"><h1 className="truncate font-display text-xl font-bold">{tracker.name}</h1><p className="mt-0.5 text-[10px] font-bold uppercase tracking-[.14em] text-slate-500">{members.length} members · {tracker.status === 'archived' ? 'Archived' : 'Active'}</p></div><div className="flex items-center"><button type="button" onClick={share} disabled={sharing || !membership.can_manage_members} className={`flex size-10 items-center justify-center rounded-full text-slate-700 ${!membership.can_manage_members ? 'hidden' : ''}`} aria-label="Share tracker"><Share2 size={20}/></button><Link href={route('trackers.members.index', tracker.id)} className="flex size-10 items-center justify-center rounded-full text-slate-700"><Users size={22}/></Link></div></div>}>
        <Head title={tracker.name} />
        <div className="page-wrap max-w-4xl">{flash.success && <div className="mb-4 rounded-2xl bg-[#e9fbf0] px-4 py-3 text-sm font-medium text-[#0d9b4b]">{flash.success}</div>}
            <BalanceCard balance={ownBalance} currency={tracker.currency_code} obligations={debts} currentUserId={currentUserId} people={people} settlementHref={membership.can_settle ? route('trackers.settlements.create', tracker.id) : null} />
            <Link href={route('trackers.conversation.index', tracker.id)} className="mt-4 flex items-center gap-4 rounded-[1.45rem] border border-[#c8f1d8] bg-white px-5 py-4 shadow-[0_3px_10px_rgba(15,23,42,.035)] transition hover:border-[#8ce4af] hover:bg-[#f9fffb]">
                <span className="relative flex size-11 items-center justify-center rounded-2xl bg-[#e8faef] text-[#16b85b]"><MessageCircle size={21}/>{unreadMessages > 0 && <span className="absolute -right-2 -top-2 flex min-w-5 items-center justify-center rounded-full border-2 border-white bg-rose-500 px-1 text-[10px] font-bold leading-5 text-white" aria-label={`${unreadMessages} unread messages`}>{unreadMessages > 99 ? '99+' : unreadMessages}</span>}</span>
                <span className="min-w-0 flex-1"><span className="block font-display text-lg font-bold text-slate-900">Conversation</span><span className="mt-0.5 block truncate text-sm text-slate-500">Message everyone in this tracker{unreadNotificationsCount > 0 ? ` · ${unreadNotificationsCount > 99 ? '99+' : unreadNotificationsCount} new updates` : ''}</span></span>
                <span className="flex items-center gap-2"><span className="text-xs font-bold text-rose-500">{unreadMessages > 0 ? `${unreadMessages > 99 ? '99+' : unreadMessages} new` : ''}</span><ChevronRight size={20} className="shrink-0 text-[#26bf67]"/></span>
            </Link>
            <div className="mt-7 flex overflow-x-auto border-b border-slate-200"><button onClick={() => setTab('transactions')} className={`min-w-28 flex-1 border-b-2 px-2 py-4 text-[10px] font-bold uppercase tracking-[.1em] sm:text-xs ${tab === 'transactions' ? 'border-[#2ecc70] text-[#16b85b]' : 'border-transparent text-slate-400'}`}>Transactions</button><button onClick={() => setTab('balances')} className={`min-w-24 flex-1 border-b-2 px-2 py-4 text-[10px] font-bold uppercase tracking-[.1em] sm:text-xs ${tab === 'balances' ? 'border-[#2ecc70] text-[#16b85b]' : 'border-transparent text-slate-400'}`}>Balances</button><button onClick={() => setTab('personal')} className={`min-w-28 flex-1 border-b-2 px-2 py-4 text-[10px] font-bold uppercase tracking-[.1em] sm:text-xs ${tab === 'personal' ? 'border-[#2ecc70] text-[#16b85b]' : 'border-transparent text-slate-400'}`}>My Activity</button><button onClick={() => setTab('mine')} className={`min-w-28 flex-1 border-b-2 px-2 py-4 text-[10px] font-bold uppercase tracking-[.1em] sm:text-xs ${tab === 'mine' ? 'border-[#2ecc70] text-[#16b85b]' : 'border-transparent text-slate-400'}`}>My Expenses</button></div>
            {tab === 'personal' && <section className="mt-7"><h2 className="font-display text-2xl font-bold">My Activity</h2><p className="mt-1 text-sm text-slate-500">Your complete expense and settlement history, including pending, declined, completed, and reversed payments.</p>{personalTransactions.length === 0 ? <div className="mt-4 ss-card p-10 text-center"><p className="font-bold">No personal activity yet</p><p className="mt-1 text-sm text-slate-500">Your expenses and settlements will appear here.</p></div> : <div className="mt-4 overflow-hidden rounded-[1.65rem] border border-slate-100 bg-white">{personalTransactions.map((item) => { const outgoing = item.direction === 'out'; const incoming = item.direction === 'in'; const Icon = outgoing ? ArrowUpRight : incoming ? ArrowDownLeft : ReceiptText; const amountColor = item.status === 'reversed' ? 'text-slate-400 line-through' : outgoing ? 'text-rose-600' : incoming ? 'text-[#0aa446]' : 'text-slate-900'; return <div key={`${item.type}-${item.id}`} className="flex items-center gap-4 border-b border-slate-100 px-4 py-4 last:border-0"><span className={`flex size-12 shrink-0 items-center justify-center rounded-2xl ${item.status === 'reversed' ? 'bg-slate-100 text-slate-400' : outgoing ? 'bg-rose-50 text-rose-600' : incoming ? 'bg-[#e8faef] text-[#0aa446]' : 'bg-amber-50 text-amber-600'}`}><Icon size={21}/></span><div className="min-w-0 flex-1"><h3 className="truncate font-bold">{item.title}</h3><p className="mt-1 text-sm capitalize text-slate-500">{shortDate(item.date)}{item.type === 'settlement' ? ` · ${item.status}` : ' · expense added'}</p></div><div className="text-right"><p className={`font-display text-lg font-bold ${amountColor}`}>{outgoing ? '−' : incoming ? '+' : ''}{money(item.amount_minor, tracker.currency_code)}</p><p className="mt-1 text-[10px] font-bold uppercase tracking-wider text-slate-400">{outgoing ? 'Outgoing' : incoming ? 'Incoming' : 'Expense'}</p></div></div>; })}</div>}</section>}
            {tab === 'mine' && <section className="mt-7"><div className="rounded-[1.65rem] border-2 border-[#2ecc70] bg-[#effcf4] p-6"><p className="eyebrow">Total you paid on this trip</p><p className="mt-3 text-money-xl text-[#16ad55]">{money(myExpenseTotalMinor, tracker.currency_code)}</p><p className="mt-2 text-sm text-slate-500">Across {myExpenses.length} expense{myExpenses.length === 1 ? '' : 's'}</p></div><h2 className="mt-7 font-display text-2xl font-bold">My Expenses</h2>{myExpenses.length === 0 ? <div className="mt-4 ss-card p-10 text-center"><p className="font-bold">You have not paid for an expense yet.</p><p className="mt-1 text-sm text-slate-500">Expenses where you are selected as Paid by will appear here.</p></div> : <div className="mt-4 overflow-hidden rounded-[1.65rem] border border-slate-100 bg-white">{myExpenses.map((expense, index) => <div key={expense.id} className="flex items-center border-b border-slate-100 last:border-0"><Link href={route('trackers.expenses.show', [tracker.id, expense.id])} className="flex min-w-0 flex-1 items-center gap-4 px-4 py-4 hover:bg-slate-50"><span className={`flex size-12 shrink-0 items-center justify-center rounded-2xl text-xl ${index % 2 ? 'bg-[#fff1df]' : 'bg-[#e6faef]'}`}>{category[index % category.length]}</span><div className="min-w-0 flex-1"><h3 className="truncate font-display text-lg font-bold">{expense.description}</h3><p className="mt-1 text-sm text-slate-500">{shortDate(expense.expense_date)}</p></div><p className="shrink-0 font-display text-lg font-bold">{money(expense.amount_minor, tracker.currency_code)}</p></Link>{membership.can_manage_finances && <button type="button" onClick={() => destroyExpense(expense)} className="mr-3 flex size-10 shrink-0 items-center justify-center rounded-xl border border-rose-200 text-rose-600" aria-label={`Delete ${expense.description}`}><Trash2 size={17}/></button>}</div>)}</div>}</section>}
            {tab === 'transactions' && <section className="mt-7"><div className="flex items-center justify-between gap-3"><h2 className="font-display text-2xl font-bold">Recent Transactions</h2>{membership.can_manage_finances && <Link href={route('trackers.expenses.create', tracker.id)} className="ss-button h-11 shrink-0 px-4">Add expense</Link>}</div>{expenses.length === 0 ? <div className="mt-5 ss-card p-10 text-center"><p className="font-bold">No Expenses yet</p><p className="mt-1 text-sm text-slate-500">Add the first shared expense to begin.</p>{membership.can_manage_finances && <Link href={route('trackers.expenses.create', tracker.id)} className="ss-button mt-5">Add expense</Link>}</div> : <div className="mt-4 overflow-hidden rounded-[1.65rem] border border-slate-100 bg-white">{expenses.map((expense, index) => <Link key={expense.id} href={route('trackers.expenses.show', [tracker.id, expense.id])} className="flex items-center gap-4 border-b border-slate-100 px-4 py-4 last:border-0 hover:bg-slate-50"><span className={`flex size-14 shrink-0 items-center justify-center rounded-2xl text-2xl ${index % 2 ? 'bg-[#fff1df]' : 'bg-[#e6faef]'}`}>{category[index % category.length]}</span><div className="min-w-0 flex-1"><h3 className="truncate font-display text-lg font-bold">{expense.description}</h3><p className="mt-1 text-sm text-slate-500">Paid by {expense.payer.name} · {shortDate(expense.expense_date)}</p>{expense.comments_count > 0 && <p className="mt-1 flex items-center gap-1 text-xs font-medium text-[#1bbb61]"><MessageCircle size={13}/>{expense.comments_count} comment{expense.comments_count === 1 ? '' : 's'}</p>}</div><div className="text-right"><p className="font-display text-lg font-bold">{money(expense.amount_minor, tracker.currency_code)}</p><p className="mt-1 text-xs text-slate-400">{shortDate(expense.expense_date)}</p></div><ChevronRight size={17} className="hidden text-slate-300 sm:block"/></Link>)}</div>}<p className="mt-8 text-center text-sm text-slate-400">Showing recent tracker activity</p></section>}
            {tab === 'balances' && <section className="mt-7"><h2 className="font-display text-2xl font-bold">Who needs to pay</h2><p className="mt-1 text-sm text-slate-500">Each person’s outstanding obligation to the member who actually spent.</p>{debts.length ? <div className="mt-4 space-y-3">{debts.map((debt, index) => { const fromYou = Number(debt.from_user_id) === Number(currentUserId); const toYou = Number(debt.to_user_id) === Number(currentUserId); const fromName = fromYou ? 'You' : people[debt.from_user_id]; const toName = toYou ? 'You' : people[debt.to_user_id]; return <div key={`${debt.from_user_id}-${debt.to_user_id}`} className="ss-card flex items-center gap-3 p-4"><Avatar name={fromName} index={index}/><div className="flex min-w-0 flex-1 items-center gap-2 font-semibold text-slate-800"><span className="truncate">{fromName}</span><span className="shrink-0 text-slate-400">→</span><span className="truncate">{toName}</span></div><p className={`shrink-0 font-display text-xl font-bold ${fromYou ? 'text-rose-600' : toYou ? 'text-[#0aa446]' : 'text-slate-800'}`}>{money(debt.amount_minor, tracker.currency_code)}</p></div>; })}</div> : <div className="mt-4 ss-card p-8 text-center"><p className="font-bold">Everyone is settled up</p><p className="mt-1 text-sm text-slate-500">No one needs to pay anyone right now.</p></div>}</section>}
            {membership.can_manage_lifecycle && tracker.status === 'active' && <section className="mt-10 rounded-[1.65rem] border border-rose-100 bg-rose-50/40 p-5"><h2 className="text-section-title">Tracker management</h2><p className="mt-1 text-sm text-slate-500">Archive keeps the full history and pauses this tracker. Delete removes it from everyone’s lists.</p><div className="mt-4 flex flex-wrap gap-3"><button type="button" onClick={archive} className="ss-button-secondary h-11 gap-2 px-4"><Archive size={17}/>Archive tracker</button><button type="button" onClick={destroy} className="inline-flex h-11 items-center justify-center gap-2 rounded-2xl border border-rose-200 bg-white px-4 text-sm font-semibold text-rose-600 transition hover:bg-rose-50"><Trash2 size={17}/>Delete tracker</button></div></section>}
        </div>
    </AuthenticatedLayout>;
}
