import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link, router, useForm } from '@inertiajs/react';
import { Pencil, Plus, Trash2, X } from 'lucide-react';
import { useState } from 'react';

const money = (amount, currency = 'PHP') => new Intl.NumberFormat('en-PH', { style: 'currency', currency }).format((amount || 0) / 100);
const amountInput = (amount) => ((amount || 0) / 100).toFixed(2);

function SmallForm({ title, action, initial, children, method = 'post', onSuccess, className = '' }) {
    const form = useForm(initial);
    const submit = (event) => {
        event.preventDefault();
        form[method](action, { preserveScroll: true, onSuccess: () => { form.reset(); onSuccess?.(); } });
    };

    return <form onSubmit={submit} className={`ss-card p-5 ${className}`}>
        <h2 className="font-display text-lg font-bold">{title}</h2>
        <div className="mt-4 space-y-3">{children(form)}{Object.values(form.errors).map((error) => <p className="text-sm font-medium text-rose-600" key={error}>{error}</p>)}<button className="ss-button h-11 w-full" disabled={form.processing}>Save</button></div>
    </form>;
}

function IconButton({ label, children, onClick, danger = false }) {
    return <button type="button" onClick={onClick} className={`rounded-lg p-2 ${danger ? 'text-rose-600 hover:bg-rose-50' : 'text-slate-500 hover:bg-slate-100'}`} aria-label={label} title={label}>{children}</button>;
}

export default function Accounts({ settings, accounts, buckets, commitments }) {
    const [addingAccount, setAddingAccount] = useState(false);
    const [editingAccount, setEditingAccount] = useState(null);
    const [addingReserve, setAddingReserve] = useState(false);
    const [editingReserve, setEditingReserve] = useState(null);
    const [addingBill, setAddingBill] = useState(false);
    const [editingBill, setEditingBill] = useState(null);
    const [editingRules, setEditingRules] = useState(false);
    const currency = settings.currency_code;
    const availableReserveTypes = ['savings', 'emergency'].filter((type) => !buckets[type]);
    const field = (form, key, placeholder, type = 'text') => <input className="ss-input h-11" value={form.data[key]} onChange={(event) => form.setData(key, event.target.value)} placeholder={placeholder} type={type} required />;
    const remove = (url, name) => {
        if (window.confirm(`Delete ${name}? This cannot be undone.`)) router.delete(url, { preserveScroll: true });
    };

    return <AuthenticatedLayout header={<div className="flex justify-between"><div><p className="eyebrow">Personal Finance</p><h1 className="font-display text-2xl font-bold">Accounts & planning</h1></div><Link href={route('home')} className="text-sm font-bold text-[#18b957]">Home</Link></div>}>
        <Head title="Personal accounts" />
        <div className="page-wrap space-y-6 pb-10">
            <section>
                <div className="flex items-center justify-between gap-4"><div><h2 className="font-display text-xl font-bold">Personal accounts</h2><p className="mt-1 text-sm text-slate-500">Banks, e-wallets, cash, and other places you keep money.</p></div><button onClick={() => setAddingAccount(true)} className="ss-button h-11 shrink-0 gap-2" disabled={addingAccount}><Plus size={18} /> Add account</button></div>
                <div className="mt-4 grid gap-4 md:grid-cols-2">
                    {accounts.map((account) => <div className="ss-card p-5" key={account.id}><div className="flex items-start justify-between gap-2"><div><b>{account.name}</b><p className="mt-1 text-xs text-slate-500">{account.type}</p></div><div className="flex"><IconButton label={`Edit ${account.name}`} onClick={() => setEditingAccount(account)}><Pencil size={17} /></IconButton><IconButton label={`Delete ${account.name}`} danger onClick={() => remove(route('personal.accounts.destroy', account.id), account.name)}><Trash2 size={17} /></IconButton></div></div><p className="mt-3 text-2xl font-bold">{money(account.balance_minor, currency)}</p><p className="mt-1 text-xs text-slate-500">{account.last_reconciled_at ? `Verified ${new Date(account.last_reconciled_at).toLocaleDateString()}` : 'Needs checking'}</p></div>)}
                </div>
                {addingAccount && <div className="mt-4"><SmallForm title="Add account" action={route('personal.accounts.store')} initial={{ name: '', type: 'bank', opening_balance: '0' }} className="relative" onSuccess={() => setAddingAccount(false)}>{(form) => <><button type="button" onClick={() => setAddingAccount(false)} className="absolute right-5 top-5 text-slate-400" aria-label="Close add account form"><X size={18} /></button><input className="ss-input h-11" value={form.data.name} onChange={(event) => form.setData('name', event.target.value)} placeholder="Maribank, GCash…" required /><select className="ss-input h-11" value={form.data.type} onChange={(event) => form.setData('type', event.target.value)}><option value="bank">Bank</option><option value="e_wallet">E-wallet</option><option value="cash">Cash</option><option value="other">Other</option></select>{field(form, 'opening_balance', 'Current balance', 'number')}</>}</SmallForm></div>}
                {editingAccount && <div className="mt-4"><SmallForm title={`Edit ${editingAccount.name}`} action={route('personal.accounts.update', editingAccount.id)} method="patch" initial={{ name: editingAccount.name, type: editingAccount.type, cash_balance: editingAccount.name === 'Cash' && editingAccount.type === 'cash' ? amountInput(editingAccount.balance_minor) : '' }} className="relative" onSuccess={() => setEditingAccount(null)}>{(form) => <><button type="button" onClick={() => setEditingAccount(null)} className="absolute right-5 top-5 text-slate-400" aria-label="Close edit account form"><X size={18} /></button>{editingAccount.name === 'Cash' && editingAccount.type === 'cash' ? <><p className="text-sm font-medium">Cash account</p>{field(form, 'cash_balance', 'Cash currently on hand', 'number')}<p className="text-xs text-slate-500">Saving records any balance change as an adjustment.</p></> : <><input className="ss-input h-11" value={form.data.name} onChange={(event) => form.setData('name', event.target.value)} required /><select className="ss-input h-11" value={form.data.type} onChange={(event) => form.setData('type', event.target.value)}><option value="bank">Bank</option><option value="e_wallet">E-wallet</option><option value="cash">Cash</option><option value="other">Other</option></select><p className="text-xs text-slate-500">To correct a balance, use Reconcile account below so the change is recorded.</p></>}</>}</SmallForm></div>}
            </section>

            <div className="grid gap-5 lg:grid-cols-2">
                <section className="ss-card p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="font-display text-lg font-bold">Reserve money</h2><p className="mt-1 text-sm text-slate-500">Savings or emergency money set aside.</p></div><button onClick={() => setAddingReserve(true)} className="ss-button h-10 shrink-0 gap-1.5" disabled={addingReserve || availableReserveTypes.length === 0}><Plus size={16} /> Add reserve</button></div><div className="mt-4 space-y-2">{Object.values(buckets).map((bucket) => <div key={bucket.id} className="flex items-center justify-between rounded-xl bg-slate-50 px-3 py-2"><div><b className="capitalize">{bucket.type === 'emergency' ? 'Emergency fund' : bucket.type}</b><p className="text-xs text-slate-500">Protected {money(bucket.reserved_minor, currency)} · Target {money(bucket.target_minor, currency)}</p></div><div className="flex"><IconButton label={`Edit ${bucket.type}`} onClick={() => setEditingReserve(bucket)}><Pencil size={16} /></IconButton><IconButton label={`Delete ${bucket.type}`} danger onClick={() => remove(route('personal.buckets.destroy', bucket.id), `${bucket.type} reserve`)}><Trash2 size={16} /></IconButton></div></div>)}</div>{addingReserve && <SmallForm title="Add reserve" action={route('personal.buckets.save')} method="put" initial={{ type: availableReserveTypes[0], target: '0', reserved: '0' }} className="relative mt-4" onSuccess={() => setAddingReserve(false)}>{(form) => <><button type="button" onClick={() => setAddingReserve(false)} className="absolute right-5 top-5 text-slate-400" aria-label="Close add reserve form"><X size={18} /></button><select className="ss-input h-11" value={form.data.type} onChange={(event) => form.setData('type', event.target.value)}>{availableReserveTypes.map((type) => <option key={type} value={type}>{type === 'emergency' ? 'Emergency fund' : 'Savings'}</option>)}</select>{field(form, 'target', 'Target amount', 'number')}{field(form, 'reserved', 'Currently protected', 'number')}</>}</SmallForm>}{editingReserve && <SmallForm title={`Edit ${editingReserve.type === 'emergency' ? 'Emergency fund' : 'Savings'} reserve`} action={route('personal.buckets.save')} method="put" initial={{ type: editingReserve.type, target: amountInput(editingReserve.target_minor), reserved: amountInput(editingReserve.reserved_minor) }} className="relative mt-4" onSuccess={() => setEditingReserve(null)}>{(form) => <><button type="button" onClick={() => setEditingReserve(null)} className="absolute right-5 top-5 text-slate-400" aria-label="Close edit reserve form"><X size={18} /></button><p className="text-sm font-medium capitalize">{editingReserve.type === 'emergency' ? 'Emergency fund' : 'Savings'}</p>{field(form, 'target', 'Target amount', 'number')}{field(form, 'reserved', 'Currently protected', 'number')}</>}</SmallForm>}</section>
                <section className="ss-card p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="font-display text-lg font-bold">Recurring bills</h2><p className="mt-1 text-sm text-slate-500">Each bill you need to reserve for.</p></div><button onClick={() => setAddingBill(true)} className="ss-button h-10 shrink-0 gap-1.5" disabled={addingBill}><Plus size={16} /> Add bill</button></div><div className="mt-4 space-y-2">{commitments.map((bill) => <div key={bill.id} className="flex items-center justify-between rounded-xl bg-slate-50 px-3 py-2"><div><b>{bill.name}</b><p className="text-xs text-slate-500">{money(bill.amount_minor, currency)} · Due every {bill.due_day}</p></div><div className="flex"><IconButton label={`Edit ${bill.name}`} onClick={() => setEditingBill(bill)}><Pencil size={16} /></IconButton><IconButton label={`Delete ${bill.name}`} danger onClick={() => remove(route('personal.commitments.destroy', bill.id), bill.name)}><Trash2 size={16} /></IconButton></div></div>)}</div>{addingBill && <SmallForm title="Add recurring bill" action={route('personal.commitments.store')} initial={{ name: '', amount: '', due_day: '15', category: 'Bills' }} className="relative mt-4" onSuccess={() => setAddingBill(false)}>{(form) => <><button type="button" onClick={() => setAddingBill(false)} className="absolute right-5 top-5 text-slate-400" aria-label="Close add bill form"><X size={18} /></button>{field(form, 'name', 'Bill name')}{field(form, 'amount', 'Amount', 'number')}{field(form, 'due_day', 'Due day', 'number')}</>}</SmallForm>}{editingBill && <SmallForm title={`Edit ${editingBill.name}`} action={route('personal.commitments.update', editingBill.id)} method="patch" initial={{ name: editingBill.name, amount: amountInput(editingBill.amount_minor), due_day: editingBill.due_day, category: editingBill.category }} className="relative mt-4" onSuccess={() => setEditingBill(null)}>{(form) => <><button type="button" onClick={() => setEditingBill(null)} className="absolute right-5 top-5 text-slate-400" aria-label="Close edit bill form"><X size={18} /></button>{field(form, 'name', 'Bill name')}{field(form, 'amount', 'Amount', 'number')}{field(form, 'due_day', 'Due day', 'number')}</>}</SmallForm>}</section>
            </div>

            <div className="grid gap-5 lg:grid-cols-2">
                {accounts.length > 0 && <SmallForm title="Reconcile account" action={route('personal.reconciliations.store')} initial={{ account_id: accounts[0]?.id || '', actual_balance: '', resolution: 'untracked_spending', note: '' }}>{(form) => <><select className="ss-input h-11" value={form.data.account_id} onChange={(event) => form.setData('account_id', event.target.value)}>{accounts.map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</select>{field(form, 'actual_balance', 'Actual balance', 'number')}<select className="ss-input h-11" value={form.data.resolution} onChange={(event) => form.setData('resolution', event.target.value)}><option value="untracked_spending">Untracked spending</option><option value="missing_transfer">Missing transfer</option><option value="manual_adjustment">Manual adjustment</option></select></>}</SmallForm>}
                <section className="ss-card p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="font-display text-lg font-bold">Monthly rules</h2><p className="mt-1 text-sm text-slate-500">Paydays: {settings.payday_day}{settings.second_payday_day ? ` and ${settings.second_payday_day}` : ''}</p><p className="mt-2 text-xs text-slate-500">Lifestyle {settings.lifestyle_percent}% · Savings {settings.savings_percent}% · Emergency {settings.emergency_percent}%</p></div><IconButton label="Edit monthly rules" onClick={() => setEditingRules(true)}><Pencil size={17} /></IconButton></div>{editingRules && <SmallForm title="Edit monthly rules" action={route('personal.settings.update')} method="patch" initial={{ payday_day: settings.payday_day, second_payday_day: settings.second_payday_day || '', lifestyle_percent: settings.lifestyle_percent, savings_percent: settings.savings_percent, emergency_percent: settings.emergency_percent }} className="relative mt-4" onSuccess={() => setEditingRules(false)}>{(form) => <><button type="button" onClick={() => setEditingRules(false)} className="absolute right-5 top-5 text-slate-400" aria-label="Close monthly rules form"><X size={18} /></button><label className="text-sm font-bold">First payday</label>{field(form, 'payday_day', 'Day of month, e.g. 15', 'number')}<label className="text-sm font-bold">Second payday</label><input className="ss-input h-11" value={form.data.second_payday_day} onChange={(event) => form.setData('second_payday_day', event.target.value)} placeholder="Day of month, e.g. 30" type="number" min="1" max="31" /><p className="text-xs text-slate-500">The dashboard uses the nearest upcoming payday.</p><label className="text-sm font-bold">Lifestyle %</label>{field(form, 'lifestyle_percent', 'Lifestyle', 'number')}<label className="text-sm font-bold">Savings %</label>{field(form, 'savings_percent', 'Savings', 'number')}<label className="text-sm font-bold">Emergency %</label>{field(form, 'emergency_percent', 'Emergency', 'number')}</>}</SmallForm>}</section>
            </div>
        </div>
    </AuthenticatedLayout>;
}
