import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import Avatar from '@/Components/Avatar';
import InputError from '@/Components/InputError';
import { money, shortDate } from '@/utils/money';
import { Head, Link, useForm } from '@inertiajs/react';
import { ChevronLeft, MessageCircle, Pencil, ReceiptText, Send } from 'lucide-react';
import { useEffect, useState } from 'react';

function Conversation({ tracker, expense, comments: initialComments, canComment, currentUserId, hasMoreComments }) {
    const [comments, setComments] = useState(initialComments);
    const [hasMore, setHasMore] = useState(hasMoreComments);
    const [loadingOlder, setLoadingOlder] = useState(false);
    const { data, setData, post, processing, errors, reset } = useForm({ body: '' });
    useEffect(() => {
        if (!window.Echo) return undefined;
        const channel = window.Echo.private(`tracker.${tracker.id}`);
        channel.listen('.expense.comment.created', ({ comment }) => {
            if (comment.expense_id === expense.id) setComments((current) => current.some((item) => item.id === comment.id) ? current : [...current, comment]);
        });
        return () => window.Echo.leave(`private-tracker.${tracker.id}`);
    }, [expense.id, tracker.id]);
    const submit = (event) => { event.preventDefault(); post(route('trackers.expenses.comments.store', [tracker.id, expense.id]), { preserveScroll: true, onSuccess: () => reset('body') }); };
    const loadOlder = async () => { if (loadingOlder || !hasMore || !comments.length) return; setLoadingOlder(true); try { const params = new URLSearchParams({ before: comments[0].created_at }); const response = await fetch(`${route('trackers.expenses.comments.older', [tracker.id, expense.id])}?${params}`, { headers: { Accept: 'application/json', 'X-Requested-With': 'XMLHttpRequest' } }); const payload = await response.json(); setComments((current) => [...payload.comments, ...current]); setHasMore(payload.has_more); } finally { setLoadingOlder(false); } };
    return <section className="mt-8 border-t border-slate-200 pt-7"><div className="flex items-center gap-2"><span className="flex size-9 items-center justify-center rounded-xl bg-[#e7f9ee] text-[#20b960]"><MessageCircle size={18}/></span><div><h3 className="font-display text-xl font-bold">Expense comments</h3><p className="text-sm text-slate-500">Discuss this expense without changing balances.</p></div></div><div className="mt-5 overflow-hidden rounded-[1.4rem] border border-slate-200 bg-white">{comments.length === 0 ? <div className="p-8 text-center"><MessageCircle className="mx-auto text-[#2ecc70]"/><p className="mt-3 font-bold">No comments yet</p><p className="mt-1 text-sm text-slate-500">Ask a question or add useful context.</p></div> : <><div className="border-b border-slate-100 px-5 py-3 text-center">{hasMore && <button onClick={loadOlder} disabled={loadingOlder} className="text-sm font-bold text-[#18ad58] disabled:opacity-50">{loadingOlder ? 'Loading…' : 'View previous comments'}</button>}</div><div className="divide-y divide-slate-100">{comments.map((comment, index) => { const own = comment.author.id === currentUserId; return <article key={comment.id} className="flex gap-3 px-5 py-4"><Avatar name={own ? 'You' : comment.author.name} index={index} size="sm"/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-baseline gap-x-2"><p className="text-sm font-bold text-slate-800">{own ? 'You' : comment.author.name}</p><p className="text-xs text-slate-400">{new Intl.DateTimeFormat('en-PH', { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }).format(new Date(comment.created_at))}</p></div><p className="mt-1 whitespace-pre-wrap break-words text-sm leading-6 text-slate-600">{comment.body}</p></div></article>; })}</div></>}</div>{canComment ? <form onSubmit={submit} className="mt-4 rounded-[1.4rem] border border-slate-200 bg-white p-3 shadow-[0_3px_10px_rgba(15,23,42,.035)]"><div className="flex items-center gap-2"><input value={data.body} onChange={(event) => setData('body', event.target.value)} placeholder="Add a comment…" maxLength="2000" className="h-11 min-w-0 flex-1 rounded-xl border-0 bg-slate-100 px-4 text-sm focus:ring-2 focus:ring-[#2ecc70]"/><button disabled={processing || !data.body.trim()} className="flex size-11 shrink-0 items-center justify-center rounded-xl bg-[#2ecc70] text-white shadow-lg disabled:opacity-50" aria-label="Post comment"><Send size={19}/></button></div><InputError message={errors.body}/></form> : <p className="mt-4 rounded-2xl bg-slate-100 px-4 py-3 text-sm text-slate-500">Viewer access can read comments but cannot add one.</p>}</section>;
}

export default function Show({ tracker, expense, canManage, canComment, currentUserId, hasMoreComments }) { return <AuthenticatedLayout header={<div className="flex items-center gap-3"><Link href={route('trackers.show', tracker.id)} className="flex size-10 shrink-0 items-center justify-center"><ChevronLeft size={28}/></Link><h1 className="ss-truncate font-display text-xl font-bold">Expense Detail</h1></div>}><Head title={expense.description}/><div className="page-wrap max-w-2xl"><section className="ss-card p-7"><div className="flex items-start justify-between gap-3"><span className="flex size-16 shrink-0 items-center justify-center rounded-2xl bg-[#e7fbef] text-[#21c469]"><ReceiptText size={30}/></span>{canManage && <Link href={route('trackers.expenses.edit', [tracker.id, expense.id])} className="ss-button-secondary h-10 shrink-0 gap-2 px-3"><Pencil size={16}/>Edit</Link>}</div><p className="mt-6 eyebrow">{shortDate(expense.expense_date)}</p><h2 className="ss-truncate mt-2 font-display text-3xl font-bold">{expense.description}</h2><p className="mt-3 text-money-xl text-[#13b95a]">{money(expense.amount_minor, tracker.currency_code)}</p><div className="mt-7 border-t border-slate-100 pt-5"><p className="text-sm text-slate-500">Paid by</p><p className="ss-truncate mt-1 font-bold">{expense.payer.name}</p>{expense.note && <><p className="mt-5 text-sm text-slate-500">Note</p><p className="mt-1 break-words text-slate-700">{expense.note}</p></>}</div></section><section className="mt-6"><h3 className="eyebrow">{expense.expense_type === 'sponsored' ? 'Sponsored (No Split)' : expense.split_method === 'quantity' ? 'Split by quantity' : 'Split equally with'}</h3><div className="mt-3 space-y-3">{expense.splits.map((split,index) => <div key={split.id} className="ss-card flex items-center gap-3 p-4"><Avatar name={split.user.name} index={index}/><p className="ss-truncate flex-1 font-bold">{split.user.name}{expense.split_method === 'quantity' && <span className="ml-2 text-sm font-normal text-slate-500">× {split.quantity}</span>}</p><p className="shrink-0 text-money-lg">{money(split.amount_minor, tracker.currency_code)}</p></div>)}</div></section><Conversation tracker={tracker} expense={expense} comments={expense.comments || []} hasMoreComments={hasMoreComments} canComment={canComment} currentUserId={currentUserId}/></div></AuthenticatedLayout>; }
