import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link, router } from '@inertiajs/react';
import { Bell, CheckCheck, Trash2 } from 'lucide-react';

export default function Index({ notifications }) {
    const open = (item) => router.patch(route('notifications.group.read', item.id), {}, { preserveScroll: true });
    const dismiss = (item) => router.delete(route('notifications.group.dismiss', item.id), { preserveScroll: true });
    return <AuthenticatedLayout header={<div className="flex items-center justify-between gap-3"><div><h1 className="font-display text-2xl font-bold">Notifications</h1><p className="mt-1 text-sm text-slate-500">Updates from your trackers</p></div>{notifications.some(item => !item.read_at) && <button className="text-sm font-bold text-[#14af55]" onClick={() => router.patch(route('notifications.read-all'))}>Mark all read</button>}</div>}><Head title="Notifications"/><div className="page-wrap max-w-3xl pb-10">{notifications.length === 0 ? <div className="ss-card p-12 text-center"><Bell className="mx-auto text-[#22c76a]" size={36}/><h2 className="mt-4 text-xl font-bold">You’re all caught up</h2><p className="mt-2 text-slate-500">New tracker updates will appear here.</p></div> : <div className="overflow-hidden rounded-[1.5rem] border border-slate-100 bg-white">{notifications.map(item => <article key={item.id} className={`flex gap-3 border-b border-slate-100 p-5 last:border-0 ${item.read_at ? '' : 'bg-[#f0fcf5]'}`}><button onClick={() => open(item)} className="min-w-0 flex-1 text-left"><div className="flex items-start justify-between gap-3"><p className="font-bold">{item.title}</p>{item.count > 1 && <span className="rounded-full bg-[#eafaf0] px-2 py-0.5 text-xs font-bold text-[#15ae54]">{item.count}</span>}</div><p className="mt-1 text-sm text-slate-600">{item.count > 1 ? `${item.count} similar updates in this tracker.` : item.body}</p><p className="mt-2 text-xs font-bold text-[#15ae54]">{item.tracker?.name || 'SplitShare'} · {item.unread_count > 1 ? `${item.unread_count} unread · ` : ''}{new Intl.DateTimeFormat('en', { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }).format(new Date(item.created_at))}</p></button><button aria-label="Dismiss notification group" className="self-start text-slate-400 hover:text-rose-500" onClick={() => dismiss(item)}><Trash2 size={17}/></button></article>)}</div>}</div></AuthenticatedLayout>;
}
