<?php

namespace App\Http\Controllers;

use App\Models\PersonalAccount;
use App\Models\PersonalBucket;
use App\Models\PersonalCommitment;
use App\Models\PersonalReconciliation;
use App\Models\PersonalTransaction;
use App\Services\PersonalFinance;
use App\Services\SmartLifestyleAlerts;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;
use Carbon\Carbon;
use Inertia\Inertia;
use Inertia\Response;

class PersonalFinanceController extends Controller
{
    public function index(Request $request, PersonalFinance $finance): Response { return Inertia::render('PersonalFinance/Home', [...$finance->summary($request->user()), 'recentTransactions'=>PersonalTransaction::where('user_id',$request->user()->id)->with('account:id,name')->latest('occurred_on')->latest()->limit(8)->get()]); }
    public function accounts(Request $request, PersonalFinance $finance): Response { return Inertia::render('PersonalFinance/Accounts', [...$finance->summary($request->user()), 'transactions'=>PersonalTransaction::where('user_id',$request->user()->id)->with('account:id,name')->latest('occurred_on')->latest()->limit(30)->get()]); }
    public function storeAccount(Request $request, PersonalFinance $finance): RedirectResponse { $data=$request->validate(['name'=>['required','string','max:100',Rule::unique('personal_accounts')->where(fn($query)=>$query->where('user_id',$request->user()->id)->where('type',$request->input('type')))],'type'=>['required','in:bank,e_wallet,cash,other'],'opening_balance'=>['required','regex:/^\d+(\.\d{1,2})?$/']]); $openingBalance=$this->minor($data['opening_balance']); DB::transaction(function()use($request,$data,$openingBalance,$finance){$account=PersonalAccount::create(['user_id'=>$request->user()->id,'name'=>$data['name'],'type'=>$data['type'],'balance_minor'=>$openingBalance,'last_reconciled_at'=>now()]);if($openingBalance){PersonalTransaction::create(['user_id'=>$request->user()->id,'personal_account_id'=>$account->id,'type'=>'income','amount_minor'=>$openingBalance,'category'=>'Starting balance','description'=>'Starting balance · '.$account->name,'occurred_on'=>today()]);$finance->allocateIncome($request->user(),$openingBalance);}}); return back()->with('success','Personal account added and allocated to your plan.'); }
    public function updateAccount(Request $request, PersonalAccount $account): RedirectResponse { $this->owned($request, $account); $data=$request->validate(['name'=>['required','string','max:100',Rule::unique('personal_accounts')->ignore($account->id)->where(fn($query)=>$query->where('user_id',$request->user()->id)->where('type',$request->input('type')))],'type'=>['required','in:bank,e_wallet,cash,other'],'cash_balance'=>['nullable','regex:/^\d+(\.\d{1,2})?$/']]); $isDefaultCash=$account->name==='Cash'&&$account->type==='cash'; DB::transaction(function()use($account,$request,$data,$isDefaultCash){$account->update(['name'=>$data['name'],'type'=>$data['type']]);if($isDefaultCash&&filled($data['cash_balance']??null)){$actual=$this->minor($data['cash_balance']);$difference=$actual-$account->balance_minor;if($difference){PersonalReconciliation::create(['personal_account_id'=>$account->id,'expected_minor'=>$account->balance_minor,'actual_minor'=>$actual,'difference_minor'=>$difference,'resolution'=>'manual_adjustment','note'=>'Cash balance updated']);PersonalTransaction::create(['user_id'=>$request->user()->id,'personal_account_id'=>$account->id,'type'=>'reconciliation','amount_minor'=>abs($difference),'category'=>'Reconciliation','description'=>'Cash balance updated','occurred_on'=>today()]);$account->update(['balance_minor'=>$actual,'last_reconciled_at'=>now()]);}}}); return back()->with('success','Personal account updated.'); }
    public function destroyAccount(Request $request, PersonalAccount $account): RedirectResponse { $this->owned($request, $account); $account->delete(); return back()->with('success','Personal account deleted.'); }
    public function storeIncome(Request $request, PersonalFinance $finance): RedirectResponse { $data=$request->validate(['income_type'=>['required','in:salary,sale,other'],'salary_period'=>['nullable','required_if:income_type,salary','in:first,second'],'description'=>['nullable','string','max:255'],'date'=>['required','date'],'entries'=>['required','array','min:1','max:10'],'entries.*.account_id'=>['required','integer'],'entries.*.amount'=>['required','regex:/^\d+(\.\d{1,2})?$/']]); $category=$data['income_type']==='salary'?'Salary · '.($data['salary_period']==='first'?'15th':'30th / 31st'):ucfirst($data['income_type']); $description=($data['description']??null)?:$category; DB::transaction(function() use($request,$data,$finance,$category,$description){ $cycle=$data['income_type']==='salary'?$finance->salaryCycle($data['date'],$data['salary_period']):null; foreach($data['entries'] as $entry){$account=$this->account($request,$entry['account_id']);$amount=$this->minor($entry['amount']);$billReserve=$cycle?$finance->salaryBillReserve($request->user(),$cycle,$amount):0;$account->increment('balance_minor',$amount);PersonalTransaction::create(['user_id'=>$request->user()->id,'personal_account_id'=>$account->id,'type'=>'income','amount_minor'=>$amount,'bill_reserved_minor'=>$billReserve,'bill_cycle_date'=>$cycle?->toDateString(),'category'=>$category,'description'=>$description,'occurred_on'=>$data['date']]);$finance->allocateIncome($request->user(),$amount-$billReserve);} }); return back()->with('success','Income recorded and allocations protected.'); }
    public function storeExpense(Request $request, SmartLifestyleAlerts $alerts): RedirectResponse { $data=$request->validate(['account_id'=>['required','integer'],'amount'=>['required','regex:/^\d+(\.\d{1,2})?$/'],'category'=>['required','string','max:60'],'description'=>['nullable','string','max:255'],'date'=>['required','date'],'commitment_id'=>['nullable','integer']]); $account=$this->account($request,$data['account_id']); $amount=$this->minor($data['amount']); if($amount>$account->balance_minor) return back()->withErrors(['amount'=>'This exceeds the selected account balance.']); $expense=DB::transaction(function() use($account,$request,$data,$amount){$account->decrement('balance_minor',$amount); return PersonalTransaction::create(['user_id'=>$request->user()->id,'personal_account_id'=>$account->id,'personal_commitment_id'=>$data['commitment_id']??null,'type'=>'expense','amount_minor'=>$amount,'category'=>$data['category'],'description'=>$data['description']??null,'occurred_on'=>$data['date']]);}); $alerts->afterLifestyleExpense($request->user(), $expense); return back()->with('success','Expense recorded.'); }
    public function transfer(Request $request): RedirectResponse { $data=$request->validate(['from_account_id'=>['required','integer','different:to_account_id'],'to_account_id'=>['required','integer'],'amount'=>['required','regex:/^\d+(\.\d{1,2})?$/'],'date'=>['required','date'],'note'=>['nullable','string','max:1000']]); $from=$this->account($request,$data['from_account_id']); $to=$this->account($request,$data['to_account_id']); $amount=$this->minor($data['amount']); if($amount>$from->balance_minor)return back()->withErrors(['amount'=>'This exceeds the source account balance.']); DB::transaction(function()use($request,$from,$to,$data,$amount){$group=(string)Str::uuid();$from->decrement('balance_minor',$amount);$to->increment('balance_minor',$amount);foreach([[$from->id,'transfer_out'],[$to->id,'transfer_in']]as[$id,$type])PersonalTransaction::create(['user_id'=>$request->user()->id,'personal_account_id'=>$id,'type'=>$type,'amount_minor'=>$amount,'category'=>'Transfer','note'=>$data['note']??null,'occurred_on'=>$data['date'],'transfer_group_id'=>$group]);});return back()->with('success','Transfer completed without affecting spending.'); }
    public function storeCommitment(Request $request): RedirectResponse { $data=$request->validate(['name'=>['required','string','max:120'],'amount'=>['required','regex:/^\d+(\.\d{1,2})?$/'],'due_day'=>['required','integer','between:1,31'],'category'=>['required','string','max:60']]); PersonalCommitment::create(['user_id'=>$request->user()->id,'name'=>$data['name'],'amount_minor'=>$this->minor($data['amount']),'due_day'=>$data['due_day'],'category'=>$data['category']]);return back()->with('success','Recurring bill reserved.'); }
    public function payCommitment(Request $request, PersonalCommitment $commitment): RedirectResponse { $this->owned($request,$commitment); $data=$request->validate(['date'=>['required','date'],'entries'=>['required','array','min:1','max:10'],'entries.*.account_id'=>['required','integer'],'entries.*.amount'=>['required','regex:/^\d+(\.\d{1,2})?$/']]); $date=Carbon::parse($data['date']); $alreadyPaid=(int)PersonalTransaction::where('user_id',$request->user()->id)->where('personal_commitment_id',$commitment->id)->where('type','expense')->whereBetween('occurred_on',[$date->copy()->startOfMonth(),$date->copy()->endOfMonth()])->sum('amount_minor'); $entries=collect($data['entries'])->map(fn($entry)=>['account'=>$this->account($request,$entry['account_id']),'amount'=>$this->minor($entry['amount'])]); $total=(int)$entries->sum('amount'); if($total>$commitment->amount_minor-$alreadyPaid)return back()->withErrors(['entries'=>'This is more than the bill amount remaining.']); foreach($entries->groupBy(fn($entry)=>$entry['account']->id) as $accountEntries){$account=$accountEntries->first()['account'];if((int)$accountEntries->sum('amount')>$account->balance_minor)return back()->withErrors(['entries'=>'One selected account does not have enough balance.']);} DB::transaction(function()use($entries,$request,$commitment,$data){foreach($entries as $entry){$entry['account']->decrement('balance_minor',$entry['amount']);PersonalTransaction::create(['user_id'=>$request->user()->id,'personal_account_id'=>$entry['account']->id,'personal_commitment_id'=>$commitment->id,'type'=>'expense','amount_minor'=>$entry['amount'],'category'=>$commitment->category,'description'=>$commitment->name,'occurred_on'=>$data['date']]);}});return back()->with('success','Bill payment recorded.'); }
    public function updateCommitment(Request $request, PersonalCommitment $commitment): RedirectResponse { $this->owned($request, $commitment); $data=$request->validate(['name'=>['required','string','max:120'],'amount'=>['required','regex:/^\d+(\.\d{1,2})?$/'],'due_day'=>['required','integer','between:1,31'],'category'=>['required','string','max:60']]); $commitment->update(['name'=>$data['name'],'amount_minor'=>$this->minor($data['amount']),'due_day'=>$data['due_day'],'category'=>$data['category']]); return back()->with('success','Recurring bill updated.'); }
    public function destroyCommitment(Request $request, PersonalCommitment $commitment): RedirectResponse { $this->owned($request, $commitment); $commitment->delete(); return back()->with('success','Recurring bill deleted.'); }
    public function saveSettings(Request $request, PersonalFinance $finance): RedirectResponse { $data=$request->validate(['payday_day'=>['required','integer','between:1,31'],'second_payday_day'=>['nullable','integer','between:1,31','different:payday_day'],'lifestyle_percent'=>['required','numeric','between:0,100'],'savings_percent'=>['required','numeric','between:0,100'],'emergency_percent'=>['required','numeric','between:0,100']]); $finance->settings($request->user())->update($data);return back()->with('success','Personal Finance settings updated.'); }
    public function saveBucket(Request $request): RedirectResponse { $data=$request->validate(['type'=>['required','in:savings,emergency'],'target'=>['required','regex:/^\d+(\.\d{1,2})?$/'],'reserved'=>['required','regex:/^\d+(\.\d{1,2})?$/']]); PersonalBucket::updateOrCreate(['user_id'=>$request->user()->id,'type'=>$data['type']],['target_minor'=>$this->minor($data['target']),'reserved_minor'=>$this->minor($data['reserved'])]); return back()->with('success','Protected money updated.'); }
    public function destroyBucket(Request $request, PersonalBucket $bucket): RedirectResponse { $this->owned($request, $bucket); $bucket->delete(); return back()->with('success','Reserve deleted.'); }
    public function reconcile(Request $request): RedirectResponse { $data=$request->validate(['account_id'=>['required','integer'],'actual_balance'=>['required','regex:/^\d+(\.\d{1,2})?$/'],'resolution'=>['required','in:untracked_spending,missing_transfer,manual_adjustment'],'note'=>['nullable','string','max:1000']]);$account=$this->account($request,$data['account_id']);$actual=$this->minor($data['actual_balance']);$difference=$actual-$account->balance_minor;DB::transaction(function()use($account,$request,$data,$actual,$difference){PersonalReconciliation::create(['personal_account_id'=>$account->id,'expected_minor'=>$account->balance_minor,'actual_minor'=>$actual,'difference_minor'=>$difference,'resolution'=>$data['resolution'],'note'=>$data['note']??null]);if($difference)PersonalTransaction::create(['user_id'=>$request->user()->id,'personal_account_id'=>$account->id,'type'=>'reconciliation','amount_minor'=>abs($difference),'category'=>'Reconciliation','description'=>$data['resolution'],'occurred_on'=>today()]);$account->update(['balance_minor'=>$actual,'last_reconciled_at'=>now()]);});return back()->with('success','Account reconciled.'); }
    private function account(Request $request,int $id): PersonalAccount { return PersonalAccount::where('user_id',$request->user()->id)->findOrFail($id); }
    private function owned(Request $request, PersonalAccount|PersonalBucket|PersonalCommitment $model): void { abort_unless($model->user_id === $request->user()->id, 404); }
    private function minor(string $amount): int {[$whole,$fraction]=array_pad(explode('.',$amount,2),2,'');return ((int)$whole*100)+(int)str_pad($fraction,2,'0');}
}
